name: 'Moderne Repo Sync'
description: 'Syncs a git repository to another destination, applying Moderne transformations.'
inputs:
  origin_repo:
    description: 'The URL of the origin repository'
    required: true
  destination_repo:
    description: 'The URL of the destination repository'
    required: true
  recipes_config:
    description: 'Path to the recipes configuration file'
    required: false
    default: 'recipes.conf'
  github_token:
    description: 'GitHub Personal Access Token for authentication'
    required: true
  moderne_cli_version:
    description: 'Specific version of the Moderne CLI to use (e.g. 3.51.2)'
    required: false
  moderne_cli_stage:
    description: 'Stage of the Moderne CLI to use (stable or staging)'
    required: false
    default: 'stable'
runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Moderne CLI
      shell: bash
      env:
        MODERNE_CLI_VERSION: ${{ inputs.moderne_cli_version }}
        MODERNE_CLI_STAGE: ${{ inputs.moderne_cli_stage }}
      run: |
        # Download the specified version of moderne-cli JAR file if MODERNE_CLI_VERSION is provided,
        # otherwise download the latest version
        if [ -n "${MODERNE_CLI_VERSION}" ]; then \
            echo "Downloading version: ${MODERNE_CLI_VERSION}"; \
            curl -s --insecure --request GET --url "https://repo1.maven.org/maven2/io/moderne/moderne-cli/${MODERNE_CLI_VERSION}/moderne-cli-${MODERNE_CLI_VERSION}.jar" --output /usr/local/bin/mod.jar; \
        elif [ "${MODERNE_CLI_STAGE}" == "staging" ]; then \
            LATEST_VERSION=$(curl -s --insecure --request GET --url "https://api.github.com/repos/moderneinc/moderne-cli-releases/releases" | jq '.[0].tag_name' -r | sed "s/^v//"); \
            if [ -z "${LATEST_VERSION}" ]; then \
                echo "Failed to get latest staging version"; \
                exit 1; \
            fi; \
            echo "Downloading latest staging version: ${LATEST_VERSION}"; \
            curl -s --insecure --request GET --url "https://repo1.maven.org/maven2/io/moderne/moderne-cli/${LATEST_VERSION}/moderne-cli-${LATEST_VERSION}.jar" --output /usr/local/bin/mod.jar; \
        else \
            LATEST_VERSION=$(curl -s --insecure --request GET --url "https://api.github.com/repos/moderneinc/moderne-cli-releases/releases/latest" | jq '.tag_name' -r | sed "s/^v//"); \
            if [ -z "${LATEST_VERSION}" ]; then \
                echo "Failed to get latest stable version"; \
                exit 1; \
            fi; \
            echo "Downloading latest stable version: ${LATEST_VERSION}"; \
            curl -s --insecure --request GET --url "https://repo1.maven.org/maven2/io/moderne/moderne-cli/${LATEST_VERSION}/moderne-cli-${LATEST_VERSION}.jar" --output /usr/local/bin/mod.jar; \
        fi

        # Create a shell script 'mod' that runs the moderne-cli JAR file
        echo -e '#!/bin/sh\njava -jar /usr/local/bin/mod.jar "$@"' > /usr/local/bin/mod

        # Make the 'mod' script executable
        chmod +x /usr/local/bin/mod

    - name: Run Sync Script
      shell: bash
      env:
        ORIGIN_REPO: ${{ inputs.origin_repo }}
        DEST_REPO: ${{ inputs.destination_repo }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        # Ensure sync.sh is executable
        chmod +x ${{ github.action_path }}/sync.sh
        
        # Determine recipe config path
        if [ -n "${{ inputs.recipes_config }}" ] && [ "${{ inputs.recipes_config }}" != "recipes.conf" ]; then
            cp "${{ inputs.recipes_config }}" recipes.conf
        fi

        ${{ github.action_path }}/sync.sh
